maintainer       "Michael Deats and Brandon Sutherlin"
maintainer_email "mike.deats@sv.cmu.edu"
license          "All rights reserved"
description      "Installs/Configures a dynamic hadoop cluster"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.1.2"
supports 		 "debian"
supports 		 "ubuntu"
recipe           "hadoop::default", "Installs hadoop base libraries and conguration."
recipe           "hadoop::master", "Installs the NameNode and JobTracker packages and prepares the file system."
recipe           "hadoop::secondarynamenode", "Installs the SecondaryNameNode package and prepares the file system."
recipe           "hadoop::slave", "Installs the DataNode and TaskTracker packages."
depends          "apt"
depends		 	 "java"