maintainer       "Outbrain, Inc."
maintainer_email "nathan@outbrain.com"
license          "All rights reserved"
description      "Installs/Configures hadoop"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.1.1"
recipe           "hadoop::default", "Installs hadoop base libraries and conguration."
recipe           "hadoop::master", "Installs the NameNode and JobTracker packages and prepares the file system."
recipe           "hadoop::secondarynamenode", "Installs the SecondaryNameNode package and prepares the file system."
recipe           "hadoop::slave", "Installs the DataNode and TaskTracker packages and prepares the file system."
depends          "apt"
depends		 	 "java"
depends		 	 "ntp"
